export const currencies = [
{'coin':'Ethereum','id':80},
{'coin':'XRP', 'id':58},
{'coin':'EOS', 'id':2679},
{'coin':'Litecoin', 'id':1},
{'coin':'Bitcoin Cash', 'id':2321},
{'coin':'Tether', 'id':518},
{'coin':'Stellar', 'id':89},
{'coin':'Binance Coin', 'id':2710},
{'coin':'Cardano', 'id':257},
{'coin':'TRON', 'id':2713},
{'coin':'Bitcoin SV', 'id':33234},
{'coin':'Monero', 'id':28},
{'coin':'IOTA', 'id':447},
{'coin':'Dash', 'id':8},
{'coin':'Neo', 'id':133},
{'coin':'Maker', 'id':12377},
{'coin':'Ethereum Classic', 'id':118},
{'coin':'NEM', 'id':70},
{'coin':'Tezos', 'id':3682},
{'coin':'Zcash', 'id':134},
{'coin':'VeChain', 'id':2741},
{'coin':'Waves', 'id':113},
{'coin':'USD Coin', 'id':33285},
{'coin':'Dogecoin', 'id':2},
{'coin':'OmiseGO', 'id':232},
{'coin':'Ontology', 'id':32331},
{'coin':'Qtum', 'id':237},
{'coin':'Bitcoin Gold', 'id':285},
{'coin':'Basic Attention Token', 'id':184},
{'coin':'Decred', 'id':99},
{'coin':'Lisk', 'id':108},
{'coin':'ChainLink', 'id':2751},
{'coin':'BitShares', 'id':54},
{'coin':'0x', 'id':},
{'coin':'Augur', 'id':},
{'coin':'Zilliqa', 'id':},
{'coin':'Holo', 'id':},
{'coin':'Digibyte', 'id':},
{'coin':'Bytecoin', 'id':},
{'coin':'Nano', 'id':},
{'coin':'Bitcoin Diamond', 'id':},
{'coin':'Ravencoin', 'id':},
{'coin':'ICON', 'id':},
{'coin':'Enjin Coin', 'id':},
{'coin':'STEEM', 'id':},
{'coin':'KuCoin Shares', 'id':},
{'coin':'Huobi Token', 'id':},
{'coin':'Komodo', 'id':},
{'coin':'Bytom', 'id':},
{'coin':'Aeternity', 'id':},
{'coin':'Verge', 'id':},
{'coin':'Siacoin', 'id':},
{'coin':'TrueUSD', 'id':},
{'coin':'Stratis', 'id':},
{'coin':'E-Dinar Coin', 'id':},
{'coin':'Golem', 'id':},
{'coin':'Status Network Token', 'id':},
{'coin':'Theta Token', 'id':},
{'coin':'Ardor', 'id':},
{'coin':'Pundi X', 'id':},
{'coin':'IOStoken', 'id':},
{'coin':'Ark', 'id':},
{'coin':'REPO', 'id':},
{'coin':'GXChain', 'id':},
{'coin':'Revain', 'id':},
{'coin':'HyperCash', 'id':},
{'coin':'Digitex Futures', 'id':},
{'coin':'MaidSafeCoin', 'id':},
{'coin':'WAX', 'id':},
{'coin':'Factom', 'id':},
{'coin':'Dai', 'id':},
{'coin':'Decentraland', 'id':},
{'coin':'Monaco', 'id':},
{'coin':'Walton', 'id':},
{'coin':'QASH', 'id':},
{'coin':'Pivx', 'id':},
{'coin':'Electroneum', 'id':},
{'coin':'Aurora', 'id':},
{'coin':'MOAC', 'id':},
{'coin':'aelf', 'id':},
{'coin':'ZCoin', 'id':},
{'coin':'Enigma', 'id':},
{'coin':'Wanchain', 'id':},
{'coin':'Power Ledger', 'id':},
{'coin':'Qubitica', 'id':},
{'coin':'Nebulas Token', 'id':},
{'coin':'Loom Network', 'id':},
{'coin':'Storj', 'id':},
{'coin':'ReddCoin', 'id':},
{'coin':'Elastos', 'id':},
{'coin':'DigixDAO', 'id':},
{'coin':'TomoChain', 'id':},
{'coin':'Kyber Network', 'id':},
{'coin':'Loopring', 'id':},
{'coin':'iExec RLC', 'id':},
{'coin':'Polymath', 'id':},
{'coin':'ODEM', 'id':},
{'coin':'Bancor', 'id':},
{'coin':'MonaCoin', 'id':},
]
export default {currencies}