export const currencies = [
{'coin':'Ethereum'},
{'coin':'XRP'},
{'coin':'EOS'},
{'coin':'Litecoin'},
{'coin':'Bitcoin Cash'},
{'coin':'Tether'},
{'coin':'Stellar'},
{'coin':'Binance Coin'},
{'coin':'Cardano'},
{'coin':'TRON'},
{'coin':'Bitcoin SV'},
{'coin':'Monero'},
{'coin':'IOTA'},
{'coin':'Dash'},
{'coin':'Neo'},
{'coin':'Maker'},
{'coin':'Ethereum Classic'},
{'coin':'NEM'},
{'coin':'Tezos'},
{'coin':'Zcash'},
{'coin':'VeChain'},
{'coin':'Waves'},
{'coin':'USD Coin'},
{'coin':'Dogecoin'},
{'coin':'OmiseGO'},
{'coin':'Ontology'},
{'coin':'Qtum'},
{'coin':'Bitcoin Gold'},
{'coin':'Basic Attention Token'},
{'coin':'Decred'},
{'coin':'Lisk'},
{'coin':'ChainLink'},
{'coin':'BitShares'},
{'coin':'0x'},
{'coin':'Augur'},
{'coin':'Zilliqa'},
{'coin':'Holo'},
{'coin':'Digibyte'},
{'coin':'Bytecoin'},
{'coin':'Nano'},
{'coin':'Bitcoin Diamond'},
{'coin':'Ravencoin'},
{'coin':'ICON'},
{'coin':'Enjin Coin'},
{'coin':'STEEM'},
{'coin':'KuCoin Shares'},
{'coin':'Huobi Token'},
{'coin':'Komodo'},
{'coin':'Bytom'},
{'coin':'Aeternity'},
{'coin':'Verge'},
{'coin':'Siacoin'},
{'coin':'TrueUSD'},
{'coin':'Stratis'},
{'coin':'E-Dinar Coin'},
{'coin':'Golem'},
{'coin':'Status Network Token'},
{'coin':'Theta Token'},
{'coin':'Ardor'},
{'coin':'Pundi X'},
{'coin':'IOStoken'},
{'coin':'Ark'},
{'coin':'REPO'},
{'coin':'GXChain'},
{'coin':'Revain'},
{'coin':'HyperCash'},
{'coin':'Digitex Futures'},
{'coin':'MaidSafeCoin'},
{'coin':'WAX'},
{'coin':'Factom'},
{'coin':'Dai'},
{'coin':'Decentraland'},
{'coin':'Monaco'},
{'coin':'Walton'},
{'coin':'QASH'},
{'coin':'Pivx'},
{'coin':'Electroneum'},
{'coin':'Aurora'},
{'coin':'MOAC'},
{'coin':'aelf'},
{'coin':'ZCoin'},
{'coin':'Enigma'},
{'coin':'Wanchain'},
{'coin':'Power Ledger'},
{'coin':'Qubitica'},
{'coin':'Nebulas Token'},
{'coin':'Loom Network'},
{'coin':'Storj'},
{'coin':'ReddCoin'},
{'coin':'Elastos'},
{'coin':'DigixDAO'},
{'coin':'TomoChain'},
{'coin':'Kyber Network'},
{'coin':'Loopring'},
{'coin':'iExec RLC'},
{'coin':'Polymath'},
{'coin':'ODEM'},
{'coin':'Bancor'},
{'coin':'MonaCoin'},
]
export default {currencies}